---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/renefs/devconfig.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_files:
  - .zshrc
  - .osx.sh
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  - codeclimate
  # - doxygen
  - gettext
  # - gifsicle
  - git
  # - go
  # - gpg
  # - hub
  # - httpie
  # - iperf
  # - libevent
  - sqlite
  # - mcrypt
  # - nmap
  - node
  - nvm
  # - php
  # - ssh-copy-id
  # - cowsay
  # - readline
  - openssl
  # - pv
  - postgresql
  - python3
  - rbenv
  - sshpass
  - watchman
  # - wget
  # - wrk
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/versions


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - appcleaner
  - calibre
  - chromedriver
  - dash
  - dropbox
  - docker
  - dropbox
  - firefox
  - gas-mask
  - github
  - google-chrome
  - handbrake
  - iterm2
  - opera
  - plex-media-server
  - pgadmin4
  - poedit
  - postman
  - protonvpn
  - pycharm
  - skype
  - spotify
  - steam
  - sublime-text
  - subtitles
  - telegram
  - tomighty
  - transmission
  - transmit4
  - vlc
  - visual-studio-code
  - webstorm

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
  - { id: 497799835, name: "Xcode" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409183694, name: "Keynote" }
  - { id: 585829637, name: "Todoist" }
  - { id: 715768417, name: "Microsoft Remote Desktop" }
  - { id: 408981434, name: "iMovie" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx.sh --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  - name: travis
    state: present # present/absent/latest, default: present
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
